<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentRegistrationPortal.Domain\StudentRegistrationPortal.Domain.csproj" />
    <ProjectReference Include="..\StudentRegistrationPortal.Application\StudentRegistrationPortal.Application.csproj" />
    <ProjectReference Include="..\StudentRegistrationPortal.Infrastructure\StudentRegistrationPortal.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="7.3.1" />
  </ItemGroup>

</Project>

